automation:
 - alias: keepcat night.
   initial_state: true
   trigger:
     - platform: time
       at: "17:26:00"
   action:
     - service: shell_command.keepcat
   
 - alias: keepcat morning
   initial_state: true
   trigger:
     - platform: time
       at: "09:26:00"
   action:
     - service: shell_command.keepcat

 - alias: keepcat afternoon
   initial_state: true
   trigger:
     - platform: time
       at: "12:26:00"
   action:
     - service: shell_command.keepcat

shell_command:
   keepcat: python3 /root/src/keepcat/keepcat.py


